version: "3.8"
# docker run -d --network internal-network --name springboot-api-a --hostname springboot-api-a calevin/springboot_api:1.0
services:
  springboot-api-a:
    build: .
    restart: on-failure
    expose:
      - '80:80'
    depends_on:
      - db-mysql
    hostname: springboot-api-a
    networks:
      - internal-network
    environment:
      - MARIADB_PASS=${MARIADB_PASS}
      - SONAR_TOKEN=${SONAR_TOKEN}
  db-mysql:
    image: mariadb:10.8.3
    restart: always
    expose:
      - '3306'
    environment:
      - MARIADB_DATABASE=example
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=${MARIADB_PASS}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    networks:
      - internal-network
